"""Cookie pipeline helpers — convert API Cookie objects to runtime artifacts.

Public surface:
    build_requests_session(cookies: list[Cookie]) -> requests.Session
        For ``youtube-transcript-api`` (uses ``requests`` under the hood).

    write_netscape_cookie_file(cookies: list[Cookie], dir: Path) -> Path
        For yt-dlp ``--cookies``. Caller is responsible for deleting the file
        after the job completes.

The Cookie model lives in ``api.schemas`` and mirrors ``chrome.cookies.Cookie``
exactly. All fields except ``name``/``value``/``domain`` have sensible defaults.

``requests`` is not declared explicitly in pyproject — but
``youtube-transcript-api`` brings it as a transitive dependency, so importing
it here is safe.
"""

from __future__ import annotations

import logging
import tempfile
from pathlib import Path

import requests  # type: ignore[import-untyped]

from src.api.schemas import Cookie

log = logging.getLogger(__name__)


def build_requests_session(cookies: list[Cookie]) -> requests.Session:
    """Return a ``requests.Session`` pre-loaded with the given cookies.

    Used by ``youtube-transcript-api`` so YouTube sees us as the same logged-in
    user — needed for age-restricted videos and to dodge basic anti-abuse
    heuristics on cold IPs.
    """
    session = requests.Session()
    for cookie in cookies:
        kwargs: dict[str, object] = {
            "name": cookie.name,
            "value": cookie.value,
            "domain": cookie.domain,
            "path": cookie.path or "/",
            "secure": bool(cookie.secure),
        }
        if cookie.expires is not None:
            kwargs["expires"] = int(cookie.expires)
        # ``rest`` is the "free-form attributes" bag — HttpOnly belongs there
        # because the cookielib API doesn't expose it as a first-class kwarg.
        rest: dict[str, str] = {}
        if cookie.http_only:
            rest["HttpOnly"] = ""
        if rest:
            kwargs["rest"] = rest
        session.cookies.set(**kwargs)
    return session


# Netscape cookie file format — one cookie per line, tab-separated:
#   domain  flag  path  secure  expiration  name  value
#
# - ``flag`` is "TRUE" if the domain field is a wildcard ("supports any
#   subdomain"), conventionally "TRUE" for any domain starting with a dot.
# - ``secure`` and ``flag`` are encoded as "TRUE"/"FALSE" strings.
# - ``expiration`` is unix-epoch seconds; 0 means session cookie.
#
# yt-dlp recognises lines starting with ``# Netscape HTTP Cookie File`` as a
# valid header. ``# This is a generated file!`` is purely cosmetic.
_NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# This file was generated by tldr daemon. Do not edit.\n\n"
)


def _netscape_line(cookie: Cookie) -> str:
    domain = cookie.domain or ""
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    path = cookie.path or "/"
    secure = "TRUE" if cookie.secure else "FALSE"
    expires = int(cookie.expires) if cookie.expires is not None else 0
    # yt-dlp expects HttpOnly cookies prefixed with "#HttpOnly_" — see
    # https://yt-dlp.org/howto/cookies/. The rest of the line is unchanged.
    domain_field = f"#HttpOnly_{domain}" if cookie.http_only else domain
    return "\t".join(
        [
            domain_field,
            include_subdomains,
            path,
            secure,
            str(expires),
            cookie.name,
            cookie.value,
        ]
    ) + "\n"


def write_netscape_cookie_file(cookies: list[Cookie], dir: Path) -> Path:
    """Write ``cookies`` to a fresh Netscape-format file inside ``dir``.

    Returns the path to the file. The caller MUST ``unlink`` it afterwards;
    we don't auto-clean because yt-dlp needs the file to exist for the
    duration of the download.
    """
    dir.mkdir(parents=True, exist_ok=True)
    fd, path_str = tempfile.mkstemp(prefix="cookies_", suffix=".txt", dir=str(dir))
    path = Path(path_str)
    try:
        with open(fd, "w", encoding="utf-8") as fh:
            fh.write(_NETSCAPE_HEADER)
            for cookie in cookies:
                fh.write(_netscape_line(cookie))
    except Exception:
        path.unlink(missing_ok=True)
        raise
    return path


__all__ = ["build_requests_session", "write_netscape_cookie_file"]
